// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXHAoPxDhpeQ1XHPa8tqFf8WdJv9Om8kM',
    appId: '1:667788278243:web:a98fa2420d0fc70f5f48d6',
    messagingSenderId: '667788278243',
    projectId: 'todo-app-e0b0c',
    authDomain: 'todo-app-e0b0c.firebaseapp.com',
    storageBucket: 'todo-app-e0b0c.appspot.com',
    measurementId: 'G-1L4ESD1JJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvIiy1CE9w8qsIu0Qi7yryst3I5sHFht0',
    appId: '1:667788278243:android:fde05f6a7cd596665f48d6',
    messagingSenderId: '667788278243',
    projectId: 'todo-app-e0b0c',
    storageBucket: 'todo-app-e0b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEZPfIVeUOjZOBpE2PpuDk0hSuzFvsxs',
    appId: '1:667788278243:ios:233add4a67dae0a25f48d6',
    messagingSenderId: '667788278243',
    projectId: 'todo-app-e0b0c',
    storageBucket: 'todo-app-e0b0c.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmEZPfIVeUOjZOBpE2PpuDk0hSuzFvsxs',
    appId: '1:667788278243:ios:142cd1845e7ffa015f48d6',
    messagingSenderId: '667788278243',
    projectId: 'todo-app-e0b0c',
    storageBucket: 'todo-app-e0b0c.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
